### ISSUE TITLE
Implement DeliveryChannels as described in new documentation (parent, epic)

### ISSUE THREAD

**Issue by tomcrane** [dlcs/protagonist#489]
The protagonist being rolled out for Wellcome supports _DeliveryChannels_ - iiif-img, file, iiif-av (and no channel).

But we still only have one `ImageOptimisationPolicy` per asset, which can only apply to one of the delivery channels if an asset has multiple. This halfway-house is to get Wellcome deployed quicker, but ultimately, we need to allow each delivery channel to have its policy set. This allows for more complex combinations in future, and removes some fudging on the DDS side.

One obvious application is this: https://github.com/dlcs/protagonist/issues/460
See also https://github.com/dlcs/protagonist/issues/73#issuecomment-1621532564 for how this technique would be used for thumbnails.

The `iiif-img` channel could have one policy, and **the separate ThumbnailPolicy goes away, it's just the policy for the thumbs channel**. This needs a schema change.

Do we need to allow for multiple OptimisationPolicy per channel? 
Suggest *no* - complexity can be part of a particular policy - e.g., a single policy for iiif-av could specify multiple outputs. But we should think about the ways in which a consuming application would want to express this.

## Acceptance criteria

 - [ ] The concept of delivery Channel is reflected in the API as a resource - we have URIs for `thumbs`, `iiif-img`, `iiif-av`, `file` and more to come
 - [ ] Use the term `policy` rather than ImageOptimisationPolicy
 - [ ] For any asset, there are a set of 0..n delivery channels, each of which has a `policy`
 - [ ] There is a global set of default policies-per-channel that any customer can apply to their assets
 - [ ] You can CRUD your customer and space level policies in the portal, and view the global ones
 - [ ] Default policies-per-channel can be set at the Customer and Space level
 - [ ] A policy for a channel for an asset can be the `id` of an existing policy
 - [ ] (discuss) A policy for a channel can be specified "by value" - a one-off rather than a reference

**Comment by tomcrane** [comment]
We could rename this just `policy` because it's not always an "optimisation". A more detailed description of behaviour is given in https://github.com/dlcs/protagonist/issues/73#issuecomment-1621532564. That suggests that a delivery channel always delivers the same kind of output*, rather than it being a conceptual thing - `thumbs` always is a level 0 jpeg image service, it doesn't vary the output by source asset content type, but will certainly vary the mechanism it uses to produce that output (in this case done at ingest-time in Engine).

*The `file` channel can deliver anything but still fits this description if defined as "always delivers the original bytes of the asset".

**Comment by tomcrane** [comment]
This needs re-stating after we decide on delivery channel API approach. See the prototype documentation.

**Comment by tomcrane** [comment]
This is superseded as it is more fully described by the prototype documentation
